project:
  type: website
execute:
  freeze: auto
website:
  title: rforhta
  navbar:
    left:
      - index.qmd
      - src/01_summary.qmd
      - src/02_intro.qmd
      - src/03_references.qmd
      - src/visualisation.qmd
bibliography: rforhta.bib
format:
  html:
    theme: cosmo
editor: visual
