project:
  type: website

website:
  title: "rforhta"
  sidebar:
    style: "docked"
    search: true
    contents:
      - text: "Home"
        href: index.qmd
      - section: "Basics"
        contents: 
          - text: "Installing R"
            href: content/installr.qmd
          - text: "Git Basics"
            href: content/git.qmd


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual
