project:
  type: book
execute:
  pre-render: Rscript update_chapters.R
  freeze: auto
book:
  title: rforhta
  author: Sol Yates
  chapters:
  - index.qmd
  - src/01_summary.qmd
  - src/02_intro.qmd
  - src/03_references.qmd
bibliography: rforhta.bib
format:
  html:
    theme: cosmo
editor: visual
