name: Quarto Publish

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 5 * * 1' # Weekly on Monday at 5 AM UTC

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'
          use-public-rspm: true  # Fast binary installs
      
      - name: Install R package dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 2  # Increment this to bust cache if needed
          # extra-packages: |
          #   any::additional_package
      
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        # Uses latest stable version for fastest setup
      
      - name: Render Quarto website
        uses: quarto-dev/quarto-actions/render@v2
      
      - name: Deploy to GitHub Pages
        if: github.event_name != 'pull_request'  # Don't deploy PRs
        uses: JamesIves/github-pages-deploy-action@v4.6.4  # Latest version
        with:
          branch: gh-pages
          folder: _site
          clean: true  # Remove old files
          single-commit: true  # Keep gh-pages branch clean
